# Netlify configuration file for CNC Tools
# Updated: 17/05/2025
# Author: Deej Potter

[build]
command = "yarn build"
publish = ".next"

# Configure Netlify build environment
[build.environment]
# Updated to match Next.js 14.x requirements
NODE_VERSION = "22"
NPM_FLAGS = "--legacy-peer-deps"
NETLIFY_BUILD_DEBUG = "true"

# Plugins for the Netlify server
[[plugins]]
package = "@netlify/plugin-nextjs"
