# Netlify configuration file for CNC Tools
# Updated: 17/05/2025
# Author: Deej Potter

[build]
command = "npm run build"
publish = ".next"

# Configure Netlify build environment
[build.environment]
# Next.js 14 recommends node 20 lts.
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

# Configure Next.js build cache
[[plugins]]
package = "@netlify/plugin-nextjs"

# Add cache configuration for faster builds
[[plugins]]
package = "netlify-plugin-cache"
[plugins.inputs]
paths = [".next/cache", "node_modules/.cache"]
