services:
  - type: web
    name: cnc-tools
    runtime: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_ALGO_API_URL
        value: https://algo-api.deejpotter.com
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
